---
title: "ECIS cell response data analysis"
output: html_notebook
---

```{r}
librarian::shelf(openxlsx, magrittr,ggpubr, tidyverse, reshape2, export, gridExtra, plyr, data.table, formattable, ez)
```


```{r}
###Data
df<-fread("ECIS data.csv")
DataExplorer::create_report(df)

df1<-df %>% 
  .[seq(1, nrow(.), 10), ] %>% 
  melt(id.vars=c("time")) %>% 
    mutate(variable=gsub("[0-9]+","", variable)) %>%
  mutate(time=formattable(time, digits = 0, format = "f")) %>% 
  dplyr::rename(Time=1, Treatment=2, Signal=3) %>% 
  mutate (id= rep(1:11, 37))

head(df1)
```


```{r}
### Polynomial regression modelling
formula <- y ~ poly(x, 4, raw = TRUE)
p <- ggplot(df1, aes(Time, Signal, color = Treatment)) +
  geom_point() +
  stat_smooth(aes(fill = Treatment, color = Treatment), method = "lm", formula = formula) +
  stat_regline_equation(aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),formula = formula) +
  theme_classic()+labs(x = "Time (Hour)")
ggpar(p, palette = "aaas")
```


```{r}
###Two way repeated anova
ezANOVA(data = df1, dv = Signal, wid = id, between = Time*Treatment) 

res.aov <- aov(Signal ~ Treatment * Time + Error(id), data = df1)
summary(res.aov)
```


```{r}
###ggline plot
p<-ggline(subset(df1), x="Time", y="Signal", color="Treatment", palette = "aaas", add = c("mean_sd", "jitter"), x.text.angle=90, legend = "right", ylab = "Migration response", xlab = "Hour", add.params = list(size=1.2))
p1<-p+stat_compare_means(size=2, method="anova")
print(p1)
```


```{r}
# Select best regression model
library(leaps)
models <- regsubsets(Signal~ Treatment + Time, data = df1, nvmax = 5)
summary(models)
res.sum <- summary(models)
data.frame(
  Adj.R2 = which.max(res.sum$adjr2),
  CP = which.min(res.sum$cp),
  BIC = which.min(res.sum$bic)
)
```

